version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      - coffee-shop
    volumes:
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-user
    image: microservices-user
    environment:
      IN_DOCKER: true
      DATABASE_DSN: mysql://user:password@tcp(mysql:3306)/user_service?charset=utf8mb4&parseTime=True&loc=Local
      JWT_SECRET: 5f3d4923ba202dad5036098efa1fe856f2bb9492063eb978571bcbb4fd934edd
      PORT: 8081
    ports:
      - 8081:8081
      - 9090:9090
    volumes:
      - ./logs:/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coffee-shop

#  supplier:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile-supplier
#    image: microservices-supplier
#    environment:
#      IN_DOCKER: true
#      DATABASE_DSN: mysql://user:password@tcp(mysql:3306)/supplier_service?charset=utf8mb4&parseTime=True&loc=Local
#      PORT: 8082
#    ports:
#      - 8082:8082
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - coffee-shop
#
#  payment:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile-payment
#    image: microservices-payment
#    environment:
#      IN_DOCKER: true
#      DATABASE_DSN: mysql://user:password@tcp(mysql:3306)/payment_service?charset=utf8mb4&parseTime=True&loc=Local
#      PORT: 8083
#    ports:
#      - 8083:8083
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - coffee-shop
#
#  order:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile-order
#    image: microservices-order
#    environment:
#      IN_DOCKER: true
#      DATABASE_DSN: mysql://user:password@tcp(mysql:3306)/order_service?charset=utf8mb4&parseTime=True&loc=Local
#      PORT: 8084
#    ports:
#      - 8084:8084
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - coffee-shop
#
#  notification:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile-notification
#    image: microservices-notification
#    environment:
#      IN_DOCKER: true
#      DATABASE_DSN: mysql://user:password@tcp(mysql:3306)/notification_service?charset=utf8mb4&parseTime=True&loc=Local
#      PORT: 8085
#    ports:
#      - 8085:8085
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - coffee-shop


networks:
  coffee-shop:
    name: coffee-shop
    driver: bridge