# Step 1: Modules caching
FROM golang:1.24.3-alpine as modules
WORKDIR /modules
COPY go.mod go.sum ./
RUN go mod download

# Step 2: Builder
FROM golang:1.24.3-alpine as builder
WORKDIR /app
COPY --from=modules /go/pkg /go/pkg
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/app ./cmd/user

# Step 3: Final
FROM scratch

EXPOSE 5000

# GOPATH for scratch images is /
COPY --from=builder /bin/app /app
CMD ["/app"]